### ISSUE TITLE
Control+Shift+(key) doesn't work

### ISSUE THREAD

**Issue by fatkhanfauzi** [github/hotkey#33]
Hi,

I have tried to set data-hotkey with Control+Shift+p also Control+Shift+s but that doesn't work.
anyone can help?

the issue occurs on both in mac & windows.
the browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit)

thanks in advance.

**Comment by keithamus** [comment]
Hey @fatkhanfauzi thanks for the issue

What element are you adding the attribute to? Can you show us some of the code you have? Does `install` get called? Do other shortcuts work but those don’t? Do shortcuts work on other elements but not this one?

**Comment by fatkhanfauzi** [comment]
hi @keithamus 

yeah, install gets called and it works on Command+Shift+p (mac).
just the combination of Control+Shift+(key) that doesn't work.

However, it's weird when I added those keys to the unit tests, it doesn't raise any error.
Thanks

**Comment by keithamus** [comment]
You may find the browser is overriding the script behaviour.

**Comment by fatkhanfauzi** [comment]
not sure, as it doesn't work not only in chrome but also in firefox

**Comment by smridge** [comment]
@fatkhanfauzi  I initially had this issue as well and realized I needed to remove `Shift+` and replace with an uppercase letter as explained in https://github.com/github/hotkey/blob/main/src/hotkey.ts

`Control+Shift+s` corrected to `Control+S` solved.

**Comment by keithamus** [comment]
Oh yeaaaah! Thanks for tracking that down @smridge. It's been a while since we visited this code so I had forgotten that's the behaviour.

I'll close this - given that @smridge has the solution. If it doesnt work for you @fatkhanfauzi please let me know and I'll re-open this ticket!
