### ISSUE TITLE
Navigation in table views

### ISSUE THREAD

**Issue by andyw8** [github/hotkey#46]
:wave: Thanks for the nice library.

I know that GitHub supports keyboard navigation in views such as the Issues and Pull Request views. Was that implemented by building on top of this library, or is it using something else entirely?

(I'm hoping to implement something similar for my own app).

**Comment by smarthug** [comment]
@andyw8  It seems those keyboard shortcuts click anchor element which has data-hotkey property  (ex: data-hotkey="g i").
Since it clicks anchor, it navigates

**Comment by keithamus** [comment]
> I know that GitHub supports keyboard navigation in views such as the Issues and Pull Request views. Was that implemented by building on top of this library, or is it using something else entirely?

Yes GitHub uses this library for almost all shortcut management. You can open your browser's devtools and run `$$('[data-hotkey]')` on a GitHub web-page to see all of the available shortcuts that go through this library!

**Comment by keithamus** [comment]
I think I'll close this issue, as I feel like the question has been answered. Let us know if you have any more questions!
