### ISSUE TITLE
`eventToHotkeyString` inconsistent `shift` key behaviour on Mac

### ISSUE THREAD

**Issue by khiga8** [github/hotkey#54]
`eventToHotKeyString` outputs `?` event as `Shift+?`

Since the updates in the latest release which include a logic change to address a different bug, `eventToHotkeyString` is including`Shift` unexpectedly.

`?` ==> `Shift+?`
`!` ==> `Shift+!`

Can we revert the logic to what it was before?

Related PRs:
- https://github.com/github/hotkey/pull/40
- https://github.com/github/hotkey/pull/41
- https://github.com/github/hotkey/pull/43

**Comment by theinterned** [comment]
Moving form  a convo from another repo:

> Based off this [eventToHotkeyString test](https://github.com/github/hotkey/blob/main/test/test.js#L209), it doesn't look like an uppercase alpha character is necessarily expected

Hrm that test _is_ simulating the events though. Maybe we need to add playwright or something to that project and do some real browser tests? I will definitely test this carefully when I work on it to figure out _exactly_ what's actually happening in the browser.

**Comment by theinterned** [comment]
For helpful background; in https://github.com/github/hotkey/pull/43 @keithamus states that "on macOS the "Meta+Shift" plane is always lowercase". I just checked and this does appear to be the case
<img width="561" alt="Screenshot of Javascript console in Safari showing looked keyboard events" src="https://user-images.githubusercontent.com/2694/145648531-607a9569-7fbe-45a2-91ea-da901f98c827.png">

This is also true of special characters 
<img width="568" alt="Screen Shot 2021-12-10 at 5 22 32 PM" src="https://user-images.githubusercontent.com/2694/145648856-730e71e8-135f-4111-8564-7d5050c8f74d.png">

I _think_ what this means is that:

1. `?` is a valid shortcut if we want to leave the `Shift+` out of the string and is equivalent to `Shift+?`
2. But combined with the `metaKey`, that `?` key could be `Meta+/` on Mac. So, in order to specify that `shiftKey` is pressed,  `Meta+Shift+/` would be the required shortcut.

This leads me to think, that we should continue to require the `Shift` key in the keyboard string. What do you think @khiga8

**Comment by theinterned** [comment]
For the time being, I have taken this odd behaviour into account in our shortcuts https://github.com/github/github/commit/2c3902e14c647b14a664c832f2be5d2cb5691eee but this is pretty ugl
<img width="540" alt="Screen Shot 2021-12-10 at 5 41 05 PM" src="https://user-images.githubusercontent.com/2694/145650729-48da14ef-bbd9-4ae3-acf2-b25f9aeb5c9a.png">
y

**Comment by theinterned** [comment]
<img width="505" alt="Screen Shot 2021-12-10 at 5 57 36 PM" src="https://user-images.githubusercontent.com/2694/145651632-e850483b-3f4b-4332-9914-364166449b51.png">

Notice above that when the `Control+Meta+Shift` are pressed together the result is an upper case `event.key`! 🤔

**Comment by theinterned** [comment]
1. Use https://wicg.github.io/keyboard-map/#h-keyboard-getlayoutmap
2. Maybe polypill it? 
3. we can ask the user for their layout if the API is not available and store it in local storage .
3. store key as `event.code`
4. display key localized for user's keyboard layout using layout map

1. Maybe have UI to capture key codes
2. Store as QWERTY `keyCode`
2. show QWERTY locale by default
3. provide UI for user to select their keyboard layout (ASERTY, DVORAK etc.)

**Comment by theinterned** [comment]
Here is my proposed "logical" hotkey format:

- `ctrlKey`
- `altKey`
- `metaKey`
- `shiftKey`
- `event.code`

## Examples
1. To represent the key combination `ctrl+alt+cmd+shift+/` we would write `ctrlKey+altKey+metaKey+shiftKey+Slash`.
2. To represent `shift+cmd+k` we would write `shiftKey+metaKey+KeyK`
3. To represent `cmd+space` we would write `metaKey+Space`
4. To represent the key sequence `g i`, we would write `KeyG KeyI`

## Humanizing

We then would want to provide a formatting function that could show the above logical representations in a human readable form. 

```js
humanizeHotkey("shiftKey+metaKey+Slash") //=> "cmd+?"
```

This helper could take a keyboard layout (eg. DVORAK, AZERTY...) with QWERTY as default.

```js
humanizeHotkey("shiftKey+metaKey+Slash", { layout: "DVORAK"}) //=> "cmd+Z"
```

_event.code "Slash" maps to the "z" key on a DVORAK keyboard_

**Comment by khiga8** [comment]
1. Based on what you know, can we rely on keyboard map API at this point? Are there polyfills we could use or would we need to write our own? If we are unable to rely on the keyboard map API, have you found there other tools out there to help retrieve the humanized output given a keyboard layout? 

2. What does support (if any) for non-latin keyboard layouts look like? Are we supporting only: qwerty, dvorak, and colemak?

**Comment by theinterned** [comment]
Another thought: what if we support both `event.key` and `event.code` and let developers decide for themselves. We could use a prefix `key:?`, `key:k`, `key:K` etc. or `code:Slash`, `code:KeyK` etc. to let the developer decide between. semantic meaning and keyboard location.

This would put us back in the same place when `key` is combined with `Shift/Meta` such as `Meta+Shift+key:k`.

**Comment by theinterned** [comment]
Note: I added a [test](https://github.com/github/hotkey/pull/66#discussion_r777061585) and note in the [README](https://github.com/github/hotkey/pull/66#discussion_r777062118) about the inconsistent treatment of shift.

When working on this issue, that test and README note should be updated to account for however we resolve this!

**Comment by theinterned** [comment]
A soutien I am leaning towards is: when we encounter `Shift`, we should split the hotkey into multiple trie nodes:

For example, for the hotkey `"Shift+a"` (or `"A"`), we could produce the following trie nodes:

1. `Shift+a`
2. `Shift+A`
3. `A`

For the hotkey `"Mod+Shift+a"` (or `"Mod+A"`) ...

... on Windows, we could produce the following trie nodes:

1. `Control+Shift+a`
2. `Control+Shift+A`
3. `Control+A`

... and on Mac we could produce the following nodes:

1. `Meta+Shift+a`
2. `Meta+Shift+A`
3. `Meta+A`

**Comment by theinterned** [comment]
A separate thing I am considering is that we should support the [square-bracket syntax from VSCode for `event.code`](https://github.com/github/hotkey/issues/54#issuecomment-993815585).
