### ISSUE TITLE
Handle keypresses in elements with dotted ids

### ISSUE THREAD

**Issue by Aarononomous** [github/hotkey#58]
I'm throwing errors every time I keydown in an element with a dotted id. For example, `<div id="account.firm">`.

I think this should be resolvable by quoting and escaping the target id in the querySelector, index.ts line 23, from
```
if (!target.ownerDocument.querySelector(`[data-hotkey-scope=${target.id}]`)) return
```
to
```
if (!target.ownerDocument.querySelector(`[data-hotkey-scope="${CSS.escape(target.id)}"]`)) return
```

**Comment by keithamus** [comment]
Thanks for the report @Aarononomous! It's fixed in 1.6.1 :tada:
